Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.boot_timeout = 600

  # Global provider defaults (shared by all VMs)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # === ZONE A (AZ-1) ===
  # Simulated CIDR 10.10.1.10 -> 10.0.0->25.0/24  (Reserved -> 10.0.26.0 – 10.0.127.255)
  config.vm.define "web-public-a" do |node|
    node.vm.box = "ubuntu/jammy64"
    node.vm.hostname = "onprem-web-public-a"
    node.vm.network "private_network", ip: "10.10.1.10", virtualbox__intnet: "omniscale_vpc", netmask: "255.255.0.0"
    node.vm.provider "virtualbox" do |vb| vb.name = "omniscale-web-public-a" end
    node.vm.provision "shell", path: "provision/baseline.sh"
    node.vm.provision "shell", path: "provision/ubuntu-setup.sh"
  end

  # Simulated CIDR 10.10.4.10 -> 10.0.128->151.0/22  (Reserved -> 10.0.152.0 – 10.0.255.255 Mgmt, DMZ, DR, future)
  config.vm.define "db-private-a" do |node|
    node.vm.box = "almalinux/9"
    node.vm.hostname = "onprem-db-private-a"
    node.vm.network "private_network", ip: "10.10.4.10", virtualbox__intnet: "omniscale_vpc", netmask: "255.255.0.0"
    node.vm.provider "virtualbox" do |vb| vb.name = "omniscale-db-private-a" end
    node.vm.provision "shell", path: "provision/baseline.sh"
    node.vm.provision "shell", path: "provision/rhel-setup.sh"
  end

  # === ZONE B (AZ-2) ===
  # Simulated CIDR 10.10.1.20 -> 10.0.1.0/24
  config.vm.define "web-public-b" do |node|
    node.vm.box = "ubuntu/jammy64"
    node.vm.hostname = "onprem-web-public-b"
    node.vm.network "private_network", ip: "10.10.1.20", virtualbox__intnet: "omniscale_vpc", netmask: "255.255.0.0"
    node.vm.provider "virtualbox" do |vb| vb.name = "omniscale-web-public-b" end
    node.vm.provision "shell", path: "provision/baseline.sh"
    node.vm.provision "shell", path: "provision/ubuntu-setup.sh"
  end
  
  # Simulated CIDR 10.10.8.20 -> 10.0.132.0/22
  config.vm.define "db-private-b" do |node|
    node.vm.box = "almalinux/9"
    node.vm.hostname = "onprem-db-private-b"
    node.vm.network "private_network", ip: "10.10.8.20", virtualbox__intnet: "omniscale_vpc", netmask: "255.255.0.0"
    node.vm.provider "virtualbox" do |vb| vb.name = "omniscale-db-private-b" end
    node.vm.provision "shell", path: "provision/baseline.sh"
    node.vm.provision "shell", path: "provision/rhel-setup.sh"
  end

  # === ZONE C (AZ-3) ===
  # Simulated CIDR 10.10.3.10 -> 10.0.2.0/24
  config.vm.define "web-public-c" do |node|
    node.vm.box = "ubuntu/jammy64"
    node.vm.hostname = "onprem-web-public-c"
    node.vm.network "private_network", ip: "10.10.3.10", virtualbox__intnet: "omniscale_vpc", netmask: "255.255.0.0"
    node.vm.provider "virtualbox" do |vb| vb.name = "omniscale-web-public-c" end
    node.vm.provision "shell", path: "provision/baseline.sh"
    node.vm.provision "shell", path: "provision/ubuntu-setup.sh"
  end

  # Simulated CIDR 10.10.12.10 -> 10.0.136.0/22
  config.vm.define "db-private-c" do |node|
    node.vm.box = "almalinux/9"
    node.vm.hostname = "onprem-db-private-c"
    node.vm.network "private_network", ip: "10.10.12.10", virtualbox__intnet: "omniscale_vpc", netmask: "255.255.0.0"
    node.vm.provider "virtualbox" do |vb| vb.name = "omniscale-db-private-c" end
    node.vm.provision "shell", path: "provision/baseline.sh"
    node.vm.provision "shell", path: "provision/rhel-setup.sh"
  end
end